"""Auto-generated configuration file generated from config.toml.

Do not edit this file directly. Instead, edit the configuration file
and re-run the build process to regenerate this file.
"""
from dataclasses import dataclass, field


@dataclass(frozen=True)
class Config:
    @dataclass(frozen=True)
    class _reserved_table_names:
        collections: str = "__collections__"
        collection_tensor_fields: str = "__collection_tensor_fields__"

    reserved_table_names: _reserved_table_names = field(init=False, default_factory=_reserved_table_names)


CONFIG = Config()
