/**
 * This file is generated from the config.toml file.
 * Do not edit this file directly - instead, edit the original file and
 * run the build process to regenerate the file.
 */
#pragma once

#include <string>
#include <vector>

namespace tensordb_cpp {

namespace config {

namespace reserved_table_names {
static const std::string collections = "__collections__";
static const std::string collection_tensor_fields = "__collection_tensor_fields__";
}; // namespace reserved_table_names
}; // namespace config
} // namespace tensordb_cpp
